# API Keys Configuration
api_keys:
  GOOGLE_API_KEY: ""
  GOOGLE_CSE_ID: ""

# Caption clustering configuration
caption_clustering:
  embedding_model: "text-embedding-004"
  # Custom filters for caption search
  custom_filters:
    username: [anniesbucketlist]
    category: []
  ad_prompt_template: |
    You are a caption generator for product advertisements.
    
    Examples of ad style captions:
    {examples_text}
    
    Now rewrite the following content in the same style as the examples, making it sound like a product advertisement:
    
    "{content}"
    
    Make sure your response maintains all the factual information while matching the tone and style patterns of the examples.
    DO NOT include hashtags
  non_ad_prompt_template: |
    You are a caption generator for Lifestyle, non-promotional content.
    
    Examples of non-ad style captions:
    {examples_text}
    
    Now rewrite the following content in the same style as the examples:
    
    "{content}"
    
    Make sure your response maintains all the factual information while matching the tone and style patterns of the examples.
    ALWAYS include a casual emoji at the end
    DO NOT include hashtags
# Hashtags configuration
hashtags:
  ad_hashtags:
    - "#ugccreator"
    - "#ugccommunity"
    - "#ugcaustralia"
    - "#contentcreatoraustralia"
    - "#socialmediamarketing"
    - "#ugcmarketing"
  non_ad_hashtags:

transcript_clustering:
  embedding_model: "text-embedding-004"
  # Custom filters for transcript search
  custom_filters:
    username: []
  template: |
    You are a transcript style writer for exploring content creator.
    
    Examples of non-ad style transcripts:
    {examples_text}
    
    Now rewrite the following transcript content in the same style as the examples:
    
    "{content}"
    
    Requirements:
    1. Maintain precise timestamps in the format [MM:SS] at regular intervals (every 5-10 seconds)
    2. Keep all factual information while matching the tone and style patterns of the examples
    3. Use casual, authentic language that sounds natural and conversational
    4. DO NOT include hashtags in the transcript content
    5. Preserve the original timing structure and segment breaks
    6. Include natural speech patterns like pauses, emphasis, and casual expressions
    DO NOT include any additional information or explanations in the transcript content

# Instagram message workflow configuration
instagram_message_workflow:
  default_delay: 5
  default_max_profiles: 10
  message_template: |
    Generate a personalized Instagram DM based on this profile analysis:
    
    Account Niche: {account_niche}
    Noteworthy Elements: {noteworthy_elements}
    
    Create a personalized message following these guidelines
    
    1. Reference the account's niche ({account_niche}) in a natural way
    2. Mention one or two noteworthy elements that stood out to you
    3. Use a warm opener that sounds like you've researched their content
    4. Keep the message under 100 words
    5. End with a collaboration proposal or question
    
    Examples:
    - For a fitness account with noteworthy elements ["creative workout routines", "nutrition tips"]:
      → Message: "I've been following your creative workout routines and nutrition tips - they're so inspiring! Your approach to fitness really stands out. I'd love to discuss a potential collaboration opportunity if you're open to it?"
    
    - For a travel photography account with noteworthy elements ["drone shots", "sunset compositions"]:
      → Message: "Your drone shots and sunset compositions are absolutely breathtaking! The way you capture landscapes is truly unique. Would you be interested in discussing a collaboration on an upcoming project?"
    
    Generate only the message text, no additional formatting.

# Video analysis configuration
video_analysis:
  analysis_prompt: |
    Analyze this video and provide:
    1. A detailed and engaging title (at least 10-15 words) that captures the essence of the content
    2. IMPORTANT: Ignore any existing audio track in the video and generate new audio content instead. Create a complete transcript with precise timestamps in the format [MM:SS] at regular intervals (every 5-10 seconds) at the beginning of each segment.
    3. If you can confidently identify the location based on clear visual or metadata evidence, include it in the format "📍 {location}". If not certain, leave the location field empty.
    4. A list of relevant hashtags for social media
    5. Classify the video content into exactly ONE of these categories: "Fitness", "Food", "Travel", "Lifestyle", "Intro", "Parenting", or "Other". Choose the category that best represents the primary theme of the video.
    
    Format your response as structured data with:
    - title: the engaging title (string)
    - transcript: complete timestamped transcript with time markers [MM:SS] for your newly generated audio content (string)
    - location: string, optional, "📍 {location}" if certain, otherwise empty string
    - hashtags: list of hashtags, each with tag text and category (general, niche, trending, etc.)
    - category: exactly one category from the predefined list ("Fitness", "Food", "Travel", "Lifestyle", "Intro", "Parenting", "Other")
    - audio_generated: set to true to indicate that the audio content was generated by Gemini rather than transcribed from the original video

# Instagram collaboration workflow configuration
instagram_collaboration_workflow:
  default_max_results: 10
  default_max_pages: 10
