version: '3.8'

services:
  content-creation-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: content-creation-agent
    ports:
      - "8080:8080"  # GUI server
      - "8000:8000"  # Leads server
      - "8001:8001"  # Scraping server
      - "8002:8002"  # Captions server
    volumes:
      - ./uploads:/app/uploads
      - ./config.yaml:/app/config.yaml
      - ./.env:/app/.env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
    restart: unless-stopped